---
services:
  bench:
    image: bench:latest
    container_name: "bench"
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./:/app
    tty: true
    restart: always